### ISSUE TITLE
Deauthenticating an external network

### ISSUE THREAD

**Issue by YoavLevi** [tesa-klebeband/RTL8720dn-WiFi-Packet-Injection#2]
Hello dear,
First of all, I think this work is great and interesting! Please keep maintaining it.
I have a question I'm still not sure about - if one wants to use your code to deauth clients from an external network which the board is not authenticated into (and not the board self-transmitted network), does he only need to change the code at file "wifi_cust_tx.cpp" line 34 from:
"memcpy(&frame.access_point, src_mac, 6);"
to:
"memcpy(&frame.access_point, <some_external_mac_of_the_router>, 6);"
and it would simply work?
If so, wouldn't the current setup function in the .ino file be redundant?
If not and you think it is possible, what other modifications are needed for it to work?

Thanks in advance.

**Comment by tesa-klebeband** [comment]
The self hosted network is only required to set the channel correctly and setup some internal functions in order to even send packets. It is not needed to change anything in wifi_cust_tx.cpp as the function can just be called with a different Mac address which doesn't need to be the boards Mac address. I hope this answered your question. The code in the .ino file also does exactly that, the src_mac array can be anything.
